version: 0.2

phases:
  install:
    commands:
      - /usr/local/bin/dotnet-install.sh --channel LTS
  
  build:
    commands:
      - dotnet build -c Release ./TestApp2/TestApp2.csproj
      - dotnet publish -o dist

artifacts:
  files:
    - ./**
    - aws-windows-deployment-manifest.json